# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b834982ccd8088fe09d58ec28eaaa862186bc2b16953012750c3e51c846a048a17bf77bfb578759678d5968629343ffdc79b2f750f5440ad140a6a87515eb56

test:
  secret_key_base: 3d97759548c6f36871bdd5373dedc3a2d5e43aaa1752d19e2d523130a6b7f68a0b2f31205b6fea8fc1e607e5a449679255738debe31ad522e249d9e7f1ba0f28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
